backend:
  name: github
  repo: NightWolfGaming/nightwolfgaming-site # ← uprav na svůj repozitář
  branch: main

media_folder: "static/img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nadpis", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Obsah", name: "body", widget: "markdown" }

  - name: "recenze"
    label: "Recenze"
    folder: "content/recenze"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Název hry", name: "title", widget: "string" }
      - { label: "Platforma", name: "platform", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Obsah", name: "body", widget: "markdown" }
